{% set name = "docite" %}
{% set version = "0.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/docite-{{ version }}.tar.gz
  sha256: 832653579758212deb68cb03b9be62e6210d1c1a11f3c23b9178166a39c52a12

build:
  entry_points:
    - docite = docite.cli:run
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python
    - setuptools >=46.1.0
    - setuptools-scm >=5
    - pip
  run:
    - python
    - importlib-metadata  # [py<38]
    - pypandoc

test:
  imports:
    - docite
  commands:
    - pip check
    - docite --help
  requires:
    - pip

about:
  home: https://github.com/danibene/docite/
  summary: Some tools to format references in documentation
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - danibene
